name: Build App GCP

on:
  push:
    branches:
      - main

env:
  GKE_CLUSTER: simm-prd
  GKE_ZONE: southamerica-east1-a
  DEPLOYMENT_NAME: simm-teste-deployment
  IMAGE: simm/simm-teste
  TAG: main
  NAMESPACE: simm
  PROJECT_NAME: simm

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    env:
      VAR_1: teste
    steps:
      - name: Checkout staging
        uses: actions/checkout@v2

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCP_KEY }}
          project_id: simm-343120

      - name: Configure Docker to use the gcloud command-line tool as a credential
        run: gcloud --quiet auth configure-docker

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: Build container image
        run: docker build -t gcr.io/$PROJECT_NAME/$IMAGE:$TAG .

      - name: Push image to Google Container Registry
        run: docker push gcr.io/$PROJECT_NAME/$IMAGE:$TAG

      - name: Get the GKE credentials so we can deploy to the cluster
        run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      - name: Delete deployment
        run: kubectl delete deployment.apps/$DEPLOYMENT_NAME -n $NAMESPACE --ignore-not-found

      - name: Deploy to Google Kubernetes Engine
        run: kubectl apply -f $GITHUB_WORKSPACE/k8s/prd

      - name: Verify deployment
        run: kubectl rollout status deployment.apps/$DEPLOYMENT_NAME -n $NAMESPACE

      #- name: Microsoft Teams Notification
      #  uses: skitionek/notify-microsoft-teams@master
      #  if: always()
      #  with:
      #    webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
      #    needs: ${{ toJson(needs) }}
      #    job: ${{ toJson(job) }}
      #    steps: ${{ toJson(steps) }}
